### ISSUE TITLE
Question: lazy initialization

### ISSUE THREAD

**Issue by AxelHeathnet** [benwilcock/spring-rsocket-demo#1]
Hello, is there any particular reason you set the lazy intialization?

**Comment by benwilcock** [comment]
Hey there,

Thanks for stopping by my demo!

Lazy Initialisation just speeds up the loading times for Spring Boot. That's all. You don't have to use it, it's totally optional. Full details are here: https://spring.io/blog/2019/03/14/lazy-initialization-in-spring-boot-2-2

Cheers

Ben
